@HostAddress = http://localhost:5200

### Get Museum Hours

GET {{HostAddress}}/museum-hours?startDate=2024-12-01&page=1&limit=5
Accept: application/json

### Create Special Event

POST {{HostAddress}}/special-events
Content-Type: application/json
Accept: application/json

{
  "name": "Pirate Coding Workshop",
  "location": "Computer Room",
  "eventDescription": "Captain Blackbeard shares his love of the C...language.",
  "dates": [
    "2023-10-29",
    "2023-10-30"
  ],
  "price": 45
}

### List Special Events

GET {{HostAddress}}/special-events?page=1&limit=10
Accept: application/json

### Get Special Event

GET {{HostAddress}}/special-events/dad4bce8-f5cb-4078-a211-995864315e39
Accept: application/json

### Update Special Event

PATCH {{HostAddress}}/special-events/dad4bce8-f5cb-4078-a211-995864315e39
Content-Type: application/json
Accept: application/json

{
  "location": "On the beach.",
  "price": 15
}

### Delete Special Event

DELETE {{HostAddress}}/special-events/dad4bce8-f5cb-4078-a211-995864315e39

### Buy Museum Tickets

POST {{HostAddress}}/tickets
Content-Type: application/json
Accept: application/json

{
  "ticketType": "general",
  "ticketDate": "2023-09-07",
  "email": "visitor@example.com"
}

###
