using Microsoft.AspNetCore.OpenApi;
using Microsoft.OpenApi;

namespace SpecGuard.Sanitizers;

/// <summary>
/// Removes nonsensical regex patterns and string type alternatives from numeric schemas
/// generated by ASP.NET Core's OpenAPI support. When
/// <see cref="SpecGuardOptions.AllowStringNumerics"/> is set, the string
/// alternative and its number-shape pattern are preserved instead.
/// </summary>
internal sealed class NumericSchemaTransformer : IOpenApiSchemaTransformer
{
    private const JsonSchemaType NumericTypes = JsonSchemaType.Integer | JsonSchemaType.Number;

    private static readonly HashSet<string> GeneratedPatterns = new(StringComparer.Ordinal)
    {
        @"^-?(?:0|[1-9]\d*)$",
        @"^-?(?:0|[1-9]\d*)(?:\.\d+)?$",
        @"^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$",
    };

    private readonly SpecGuardOptions options;

    public NumericSchemaTransformer(SpecGuardOptions options) => this.options = options;

    public Task TransformAsync(
        OpenApiSchema schema,
        OpenApiSchemaTransformerContext context,
        CancellationToken cancellationToken)
    {
        if (schema.Type is not { } type || (type & NumericTypes) == 0)
        {
            return Task.CompletedTask;
        }

        if (options.AllowStringNumerics)
        {
            return Task.CompletedTask;
        }

        if (schema.Pattern is not null && GeneratedPatterns.Contains(schema.Pattern))
        {
            schema.Pattern = null;
        }

        schema.Type = type & ~JsonSchemaType.String;

        return Task.CompletedTask;
    }
}
